### ISSUE TITLE
IES_Toolkit: How IES adaptor handle Panel with multiple connectedspace names?

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/IES_Toolkit#117]
How IES adaptor handle Panel with multiple connectedspace names? @MajaLindroth @FraserGreenroyd 

This is a potential bug here with the IES adaptor - multiple surface are created for each connected space.

**Comment by BingWangUS** [comment]
This is also a question related to how GEM file handle adjacency, as @KentonPhillips-BH and I discussed before.

**Comment by FraserGreenroyd** [comment]
As discussed in the [wiki](https://github.com/BHoM/IES_Toolkit/wiki) GEM files are made up of panels which enclose spaces. 1 panel which is connected to 2 spaces is drawn twice in the GEM file per IES GEM standards, as there is no reference to 'existing' panels in the same way as other tools such as EnergyPlus, etc.

The IES_Toolkit handles panels with multiple space names by assigning that one panel to both spaces and including the data appropriately for the push and creation of GEM files. As this is correct for the GEM schema (at time of writing/version of IES supported), I will close this issue as question answered. If there are issues with the export feel free to reopen/raise new issues as appropriate :smile:
