### ISSUE TITLE
Tilted Openings

### ISSUE THREAD

**Issue by MajaLindroth** [BHoM/IES_Toolkit#125]
#### Description:
Openings that are tilted or where the bottom curve is not following a straight X or Y axis, the points are on different level, are not translated into IES correctly.

#### Expected behaviour:
That these type of openings can be pushed pushed into IES

**Comment by FraserGreenroyd** [comment]
@charliebrookerBH darn you and your models... :wink:

**Comment by charliebrookerBH** [comment]
I was frustrated with my other work yesterday and tried to work out the IES logic for this as a "fun task".... one hour later and feeling even more frustrated I gave up! Good luck @MajaLindroth!
