### ISSUE TITLE
GEM Pull (and Push) data - including space type and location

### ISSUE THREAD

**Issue by charliebrookerBH** [BHoM/IES_Toolkit#173]
#### Description:

GEM format includes space type (room, local shade, adjacent building, etc.) and location data in the file format that isn't currently being captured in Pull or Push. 

Including this would save time and expand the capability of the tool. 

I can provide details of types and subtypes when this gets implemented

![image](https://user-images.githubusercontent.com/26814591/116983343-dfe62680-acc1-11eb-89a2-134a2176248a.png)

**Comment by FraserGreenroyd** [comment]
> I can provide details of types and subtypes when this gets implemented

Can you give the details sooner to help us plan how long this might take to implement?

Also, is this only valid with certain versions of IES?

**Comment by charliebrookerBH** [comment]
Space types and location are supported by all versions of IES. Subtypes I believe were introduced in IES VE 2018, although I'm happy for us to ignore subtypes for now. 

Building Space (Room): Type = 1, Subtype = 2001
Building Space (Void): Type = 1, Subtype = 2002
Building Space (Return Air Plenum): Type = 1, Subtype = 2003
Building Space (Supply Air Plenum): Type = 1, Subtype = 2004
Adjacent Building: Type = 2, Subtype = 0
Topographical Shade: Type = 3, Subtype = 0
Local Shade: Type = 4, Subtype = 0
Translucent Shade: Type = 1, Subtype = 2102 

See example file attached 
[All_IES_Types.txt](https://github.com/BHoM/IES_Toolkit/files/6420195/All_IES_Types.txt)

**Comment by FraserGreenroyd** [comment]
How do the space types map to the [BHoM space type)(https://github.com/BHoM/BHoM/blob/master/Environment_oM/Elements/Enums/SpaceType.cs) @charliebrookerBH ?

I'm presuming all the shade types will be `Shade` in our space type, but what would the others map to to be a working connection for you?

**Comment by charliebrookerBH** [comment]
Building Space Room + Void = Undefined
Building Space Plenum (Return + Supply) = Plenum
Adjacent Building - could we add this as a **space** type? It's a space that has adiabatic boundary conditions
Shade (local + topographical + translucent) = Shade (potentially in the future we could have translucent shade as a separate type)

Note sure if I'm using **space** correctly above. Is Shade and Space two separate things? If so Adjacent Building could potentially be it's own thing. Alternatively you could just incorporate it as it's own new space type, or for simplicity also make it an "unadefined"

**Comment by FraserGreenroyd** [comment]
> Note sure if I'm using **space** correctly above. Are Shade and Space two separate things?

In BHoM land yes, `shade` are panels which provide shading (they have a `PanelType` of `Shade`) and spaces are collections of panels that form a closed volume (and have `SpaceType` such as `Bedroom`, `Kitchen`, etc.).

We would not typically pull the shades in as a space (in BHoM land, a shade panel has 0 connected spaces because they don't form volumes by themselves), but we can make sure the panels associated to that IES space type pull through as shade panels?

**Comment by charliebrookerBH** [comment]
Cool, in that case pulling is fine, it's the push that's slightly more complicated as ideally I'd like to be able to push a space to IES as a shade type. Probably best to leave how to deal with that to you experts - I guess having space type "shade" could cause confusion, but it would be a win for me IES wise, and might be the simplest solution in terms of interop.

**Comment by FraserGreenroyd** [comment]
We could group all shade panels as a single shade space and push it with a shade space type but that would be slightly trickier, but not impossible if that would be a reasonable shortcut?

**Comment by charliebrookerBH** [comment]
I'm afraid that won't work in IES. You end up with a disjoint space in IES and although I haven't tested the simulation implications, disjoint spaces are a pain to work with in IES and red flag for running shading calculations (which is a crucial aspect of modelling).

(It would actually be good to have disjoint spaces as an error check for the push but that's a separate issue). 

Ideally I'd like to be able to push breps to shades in GEM in a 1:1 brep:shade ratio

**Comment by FraserGreenroyd** [comment]
Hmm ok, that's unfortunate then. I get where you're coming from, but might need more thought on how we accomplish this within the framework of the IES_Toolkit 🤔

**Comment by charliebrookerBH** [comment]
What do you think of the idea of making "Shade" a space type as well as having a separate Shade object that sits beside Space at that level of the hierarchy?

**Comment by charliebrookerBH** [comment]
@linaeriksson and I have discussed yesterday and Lina's going to have a think about how to implement. I believe the difficulty at the moment is that the gem push doesn't have space as an input, which then makes an IES type output based on Space type input tricky.

**Comment by linaeriksson** [comment]
Maybe one solution could be to still pull the panels through, but set the PanelType as Shade, and make the code handle panels with Shade as shading in IES? Now it's currently being pulled through as both shades and spaces, what if we could make it just be shading, based on the PanelType? Like mentioned above?

**Comment by charliebrookerBH** [comment]
@linaeriksson I think that sounds like it could be the basis of a better approach. If we can assign shade panels a connected space, and then export them, then they would be able to sent to IES as either single panels or as a 3D object.
