### ISSUE TITLE
Pull of BHoM-Pushed GEM file doesn't work

### ISSUE THREAD

**Issue by rboulton-BH** [BHoM/IES_Toolkit#218]
#### Description:

Testing completed for beta release highlighted that the toolkit currently fails to Pull GEM files previously pushed by BHoM (although will still Pull GEMs from IES), see review on PR https://github.com/BHoM/IES_Toolkit/pull/211

#### Steps to reproduce:

Pull one of the GEM files created in section 1 of the IES_Toolkit test procedure. The Pull should produce the error identified in the review of #211 

#### Expected behaviour:

Toolkit should be able to Pull valid GEM files from both IES and BHoM (and any other 3rd Party assuming they're valid)

#### Test file(s):

Use test files from the IES_Toolkit test procedure

**Comment by FraserGreenroyd** [comment]
Please provide valid GEM files to pull with.
