### ISSUE TITLE
Handle push of multiple object types

### ISSUE THREAD

**Issue by rboulton-BH** [BHoM/IES_Toolkit#220]
#### Description:

Edge case discovered during the 6.1 Beta testing but as a 'feature' request it is not expected to be handled until the 6.2 milestone.

Currently IES Toolkit Push can only handle a list of Panel objects but should be adapted to ignore objects that aren't applicable.

For example, if you Pull a GEM file using the IES adapter it creates both BHoM Panels (with Openings if applicable) and Space objects. If you then try to Push this same list of objects (including both Panels & Spaces) then it results in an empty GEM file because the Push is triggered twice; once by the Panel objects (which works correctly) then again by the Space objects (which fails quietly and overwrites the successful Panel push).

**Comment by FraserGreenroyd** [comment]
On review of this while refactoring, is while it's possible to override the push, it would give a different user experience to other toolkit adapters. As such, it would be best to inform users that they shouldn't try to push objects that aren't of type `Panel` with this toolkit.
